version: "3"
services:
  app_node:
    build: .
    container_name: app_node
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: "npm run start:prod"