version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 2345:5432
    env_file:
      - .env
    restart: always
    volumes:
      - volume_postgres:/var/lib/postgres/data 

  app_node:
    build: .
    container_name: app_node
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run migrate:start"
    depends_on:
      - postgres

volumes:
  volume_postgres: